log_level: info
app_data_home: D://tmp//process-compose//home #忽略的话，默认会寻找当前用户的主目录
sys_service_name: process-compose
sys_service_desc: Process Monitoring and Management Tool
services:
    #受管服务配置
    service1: #服务名
      startup_delay: 5  #启动延迟，秒；配置后会在轮到该服务启动时延迟执行启动命令，一般用于等待上游依赖服务启动完成
      log_redirect: false #是否要重定向启动命令的日志输出到特定文件，作为服务日志（一般用于服务无法主动输出日志文件的场景）
      healthcheck: 
        enable: true    #是否启用健康检查
        restart: true   #服务失败后是否尝试重启服务
        url: http://localhost:23800/api/demo/test  #如果是web服务，可以配置健康检查接口，接口返回200认为是成功；默认仅检查进程是否仍在运行
        interval: 10    #健康检查的间隔，秒
        retries: 3      #健康检查失败多少次判断服务失败
        check_delay: 5 #启动后，多少秒后才开始第一次健康检查，避免启动较慢的服务
      start_cmd: ["./runtime/bin/java", "-jar","test.jar"] #启动命令
      depends_on:
        - service2  #依赖的服务名，hub-compose启动时会按照依赖顺序依次启动