log_level: info #日志等级
app_data_home: D://tmp//process-compose//home #所管服务的数据目录，默认是当前用户的主目录的.process-compose文件夹
sys_service_name: process-compose # 注册为系统服务的服务名
sys_service_desc: Process Monitoring and Management Tool #注册为系统服务的服务描述
services:
    #以下为受管服务配置，可配置多个服务
    service1: #服务名
      #是否要重定向启动命令的日志输出到特定文件，作为服务日志（一般用于服务无法主动输出日志文件的场景），重定向的日志会放到{app_data_home}/{service_name}/logs目录下
      log_redirect: false
      healthcheck: 
        enable: true    #是否启用健康检查
        test_type: http  #支持http,cmd,tcp,process四种方式，默认是process即检查进程是否存活
        test_target: http://localhost:23800/api/demo/test  #根据test_type的值决定测试目标，http方式需要配置http://开头的完整url，tcp方式需要配置ip:port，cmd方式需要配置待执行的命令
        timeout: 5      #健康检查的超时时间，单位秒
        interval: 10    #健康检查的间隔，单位秒
        retries: 3      #健康检查失败多少次判断服务失败
        start_period: 2 #该服务启动后所需的初始化时间，该期间不会进行健康检查
      #启动命令，这里对.的路径做了调整，指向了服务自己的主目录
      #例如 process-compose可执行文件放到了/home/nobody/app目录下
      #那么./runtime/bin/java实际的路径是/home/nobody/app/service1/runtime/bin/java
      start_cmd: ["./runtime/bin/java", "-jar","test.jar"] 
    service2:
      log_redirect: true 
      healthcheck:
        enable: true
        restart: true 
        interval: 10 
        retries: 1    
        start_period: 5
      #实际启动路径为{process-compose所在目录}/service2/test
      start_cmd: ["./test"]
      #所依赖的其它服务名，配置了依赖项的服务会等待所依赖服务的健康状态都OK后才会启动
      depends_on:
        - service1